name: sygray
favicon: null
layout_spectrum: 0.24763991590589285
typography_spectrum: 0.9139325737487525
title: Sygray
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1389589610043913
  lightness: 0.4574334006756544
  saturation: 0.46468003606423736
  rhythmicContrast: 0.23237631260417402
purpose: []
